name: CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        goos: [darwin, linux, windows]
        goarch: [amd64, arm64]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -v ./...

      - if: ${{ matrix.goos == 'windows' }}
        run: zip delta.zip delta.exe

      - if: ${{ matrix.goos != 'windows' }}
        run: tar -czf delta.tar.gz delta

      - uses: actions/upload-artifact@v3
        with:
          name: delta-${{ matrix.goos }}-${{ matrix.goarch }}.${{ matrix.goos == 'windows' && 'zip' || 'tar.gz' }}
          path: ${{ matrix.goos == 'windows' && 'delta.zip' || 'delta.tar.gz' }}

      - name: Test
        run: go test -v ./...
